<script type="text/javascript">
    jQuery(function () {
        jQuery('table').tablesorter({
            sortList:[
                [0, 1]
            ],
            widgets:['zebra'],
            headers:{
                1:{
                    sorter:false
                },
                3:{
                    sorter:false
                },
                5:{
                    sorter:false
                },
                6:{
                    sorter:false
                }
            }
        });
        jQuery('a.lightboxA').each(function(){
            jQuery(this).lightBox();
        });
    });
</script>

<div id="div-table">
    <table class="tablesorter" style="width: 100%;">
        <thead>
        <tr>
            <th>Id</th>
            <th>Título</th>
            <th>Link</th>
            <th>Texto</th>
            <th>Data</th>
            <th>Imagem</th>
            <th>&nbsp;</th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($this->timelines as $log): ?>
        <tr>
            <td><?php print (int)$log->id; ?></td>
            <td><?php print $this->escape($log->title); ?></td>
            <td><?php print $this->escape($log->link); ?></td>
            <td><?php print $this->truncate($log->content); ?></td>
            <td><?php print $this->dateToBr($log->date); ?></td>
            <td width="8%">                
                <?php if ($log->image): ?>
                <a href="<?php print UPLOAD_URL . $log->image; ?>" style="margin-right: 10px" target="_blank"
                    class="lightboxA" id="<?php print $log->id; ?>">
                    <img src="<?php print $this->baseUrl('public/styles/design/ico-image.gif');?>"/>
                </a>
                <a href="<?php print $this->url(array('module' => 'timeline', 'controller' => 'Index', 'action' => 'crop', 'id' => $log->id), 'admin', true); ?>" style="margin-right: 10px"
                    title="Cortar Imagem">
                    <img src="<?php print $this->baseUrl('public/styles/design/ico-image-edit.gif');?>"/>
                </a>
                <a href="<?php print $this->url(array('module' => 'timeline', 'controller' => 'Index', 'action' => 'image', 'id' => $log->id), 'admin', true); ?>"
                   title="Remover Imagem">
                    <img src="<?php print $this->baseUrl('public/styles/design/ico-image-delete.gif');?>"/>
                </a>
                <?php endif; ?>
            </td>
            <td width="10%" style="text-align: center;">
                <a href="<?php print $this->url(array('module' => 'timeline', 'controller' => 'Index', 'action' => 'edit', 'id' => $log->id), 'admin', true); ?>"
                   style="margin-right: 10px" title="Editar">
                    <img src="<?php print $this->baseUrl('public/styles/design/ico-edit.gif'); ?>"/>
                </a>
                <a href=" <?php print $this->url(array('module' => 'timeline', 'controller' => 'Index', 'action' => 'delete', 'id' => $log->id), 'admin', true); ?>"
                   style="margin-right: 10px" title="Deletar">
                    <img src="<?php print $this->baseUrl('public/styles/design/ico-delete.gif');?>"/>
                </a>
            </td>
        </tr>
            <?php endforeach; ?>
        <?php if (!$this->timelines->count() > 0): ?>
        <tr>
            <td colspan="6">Nenhuma evento cadastrado.</td>
        </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>
