<ul class="box">
    <li>
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'Index', 'action' => 'index'), 'adminDashboard', true) ?>">
            <span>Dashboard</span>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('module' => 'timeline', 'controller' => 'Index', 'action' => 'index'), 'admin', true) ?>">
            <span>Timeline</span>
        </a>
    </li>
    <!--<li>
        <a href="<?php #echo $this->url(array('module' => 'page', 'controller' => 'Index', 'action' => 'index'), 'admin', true) ?>">
            <span>Páginas</span>
        </a>
    </li>-->
    <li>
        <a href="<?php echo $this->url(array('module' => 'menu', 'controller' => 'Index', 'action' => 'index'), 'admin', true) ?>">
            <span>Menus</span>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'Index', 'action' => 'index'), 'admin', true) ?>">
            <span>Users</span>
        </a>
    </li>
    <?php if (Zend_Auth::getInstance()->getIdentity()->id == 1): ?>
    <li>
        <a href="<?php echo $this->url(array('module' => 'log', 'controller' => 'Index', 'action' => 'index'), 'admin', true) ?>">
            <span>Logs</span>
        </a>
    </li>
    <?php endif; ?>
</ul>