<div class="footer-cont">

    <div class="wgt wgt-g1 wgt-canais">
        <h2>Institucional</h2>
        <ul>
            <li><a href="http://jangadeiroonline.com.br/expediente/" title="Expediente">Expediente</a></li>
            <li><a href="http://jangadeiroonline.com.br/fale-conosco/" title="Fale Conosco">Fale Conosco</a></li>
            <li><a href="http://jangadeiroonline.com.br/institucional/" title="Sistema Jangadeiro">Sistema Jangadeiro</a></li>
            <li><a href="http://www.jangadeiroonline.com.br/solicitacao-de-copia/" title="Solicitação de cópia">Solicitação de cópia</a></li>
        </ul>

        <h2>TV</h2>
        <ul>
            <li><a href="http://www.jangadeiroonline.com.br/programacao/tv/" title="Assista à TV">Assista à TV</a></li>
        </ul>

        <h2>Rádio</h2>
        <ul>
            <li><a href="http://www.jangadeiroonline.com.br/programacao/fm/" title="Ouça a Rádio">Ouça a Rádio</a></li>
        </ul>
    </div>

    <div class="wgt wgt-g1 wgt-canais">
        <h2>Notícias</h2>
        <ul>
            <li><a href="http://jangadeiroonline.com.br/cat/economia/" title="Economia">Economia</a></li>
            <li><a href="http://jangadeiroonline.com.br/cat/fortaleza/" title="Fortaleza">Fortaleza</a></li>
            <li><a href="http://jangadeiroonline.com.br/cat/interior/" title="Interior">Interior</a></li>
            <li><a href="http://jangadeiroonline.com.br/cat/nacional/" title="Nacional">Nacional</a></li>
            <li><a href="http://jangadeiroonline.com.br/cat/policia/" title="Polícia">Polícia</a></li>
            <li><a href="http://jangadeiroonline.com.br/cat/politica/" title="Política">Política</a></li>
        </ul>
    </div>

    <div class="wgt wgt-g1 wgt-canais">
        <h2>Emprego</h2>
        <ul>
            <li><a href="http://empregos.jangadeiroonline.com.br/concursos" title="Concursos">Concursos</a></li>
            <li><a href="http://empregos.jangadeiroonline.com.br/cursos" title="Cursos">Cursos</a></li>
            <li><a href="http://empregos.jangadeiroonline.com.br/estagios" title="Estágios">Estágios</a></li>
            <li><a href="http://empregos.jangadeiroonline.com.br/emprego" title="Vagas">Vagas</a></li>
            <li><a href="http://empregos.jangadeiroonline.com.br/vagas-para-deficientes" title="Vagas para Deficientes">Vagas para Deficientes</a></li>
        </ul>

        <h2>Vídeos</h2>
        <ul>
            <li><a href="http://jangadeiroonline.com.br/video/" title="Últimos vídeos">Últimos vídeos</a></li>
        </ul>
    </div>

    <div class="wgt wgt-g1 wgt-canais">
        <h2>Esportes</h2>
        <ul>
            <li><a href="http://esportes.jangadeiroonline.com.br/cat/automobilismo/" title="Automobilismo">Automobilismo</a></li>
            <li><a href="http://esportes.jangadeiroonline.com.br/cat/basquete-2/" title="Basquete">Basquete</a></li>
            <li><a href="http://esportes.jangadeiroonline.com.br/cat/futebol/" title="Futebol">Futebol</a></li>
            <li><a href="http://esportes.jangadeiroonline.com.br/cat/natacao/" title="Natação">Natação</a></li>
            <li><a href="http://esportes.jangadeiroonline.com.br/cat/skate/" title="Skate">Skate</a></li>
            <li><a href="http://esportes.jangadeiroonline.com.br/cat/surf/" title="Surf">Surf</a></li>
            <li><a href="http://esportes.jangadeiroonline.com.br/cat/volei/" title="Vôlei">Vôlei</a></li>
        </ul>
    </div>

    <div class="wgt wgt-g1 wgt-canais">
        <h2>comunidade</h2>
        <ul>
            <li><a href="http://comunidade.jangadeiroonline.com.br/cat/cultura/" title="Cultura">Cultura</a></li>
            <li><a href="http://comunidade.jangadeiroonline.com.br/cat/educacao/" title="Educação">Educação</a></li>
            <li><a href="http://comunidade.jangadeiroonline.com.br/cat/infraestrutura/" title="Infraestrutura">Infraestrutura</a></li>
            <li><a href="http://comunidade.jangadeiroonline.com.br/cat/saude/" title="Saúde">Saúde</a></li>
            <li><a href="http://comunidade.jangadeiroonline.com.br/cat/seguranca-publica/" title="Segurança Pública">Segurança Pública</a></li>
            <li><a href="http://comunidade.jangadeiroonline.com.br/cat/servicos-nos-bairros/" title="Serviços nos Bairros">Serviços nos Bairros</a></li>
            <li><a href="http://comunidade.jangadeiroonline.com.br/cat/transporte/" title="Transporte">Transporte</a></li>
        </ul>
    </div>

    <div class="wgt wgt-g1 wgt-canais">
        <h2>Outras Redes</h2>
        <ul class="redes">
            <li><a href="http://twitter.com/JangaOnline" class="twr" title="Twitter"><div class="ir ico"></div> Twitter</a></li>
            <li><a href="http://jangadeiroonline.com.br/redes-sociais/orkut/" class="okt" title="Orkut"><div class="ir ico"></div> Orkut</a></li>
            <li><a href="http://www.facebook.com/pages/Sistema-Jangadeiro/112400412142711" class="fcb" title="Facebook"><div class="ir ico"></div> Facebook</a></li>
            <li><a href="http://jangadeiroonline.com.br/feed/" class="rss" title="RSS"><div class="ir ico"></div> RSS</a></li>
        </ul>
    </div>
    <div class="clear"></div>
</div>