<!-- CAPA -->
<script type="text/javascript">
    function gerarCapa() {
        var answer = confirm("Deseja gerar a capa?")
        if (answer) {
            document.capaForm.submit();
        }
    }
</script>
<!-- Button -->
<div class="btn-box">
    <div class="btn-top"></div>
    <div class="btn">
        <dl>
            <dt><a href="<?php print $this->baseUrl('test'); ?>" target="_blank">Visualizar Capa</a>
            </dt>
            <dd>Ver prévia da capa</dd>
        </dl>
    </div>
    <!-- /btn -->
    <div class="btn-bottom"></div>
</div>
<!-- /Button -->
<!-- Button -->
<div class="btn-box">
    <div class="btn-top"></div>
    <div class="btn">
        <dl>
            <dt>

            <form action="<?php print $this->baseUrl('generate'); ?>" method="post" name="capaForm">
                <a href="javascript: gerarCapa();">Gerar Capa</a>
                <input type="submit" class="btn-list" style="display: none;">
            </form>
            </dt>
            <dd>Gerar página estática para capa</dd>
        </dl>
    </div>
    <!-- /btn -->
    <div class="btn-bottom"></div>
</div>
<!-- /Button -->
<!-- /CAPA -->

<!-- Button -->
<div class="btn-box">
    <div class="btn-top"></div>
    <div class="btn">
        <dl>
            <dt><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'Index', 'action' => 'opengraph'), 'dashboard', true) ?>">Facebook OpenGraph</a>
            </dt>
            <dd>Editar informações do OpenGraph</dd>
        </dl>
    </div>
    <!-- /btn -->
    <div class="btn-bottom"></div>
</div>
<!-- /Button -->