<!-- Button -->
<div class="btn-box">
    <div class="btn-top"></div>
    <div class="btn">
        <dl>
            <dt><a
                href="<?php echo $this->url(array('module' => 'menu', 'controller' => 'Index', 'action' => 'index'), 'admin', true) ?>">Listar</a>
                (<?php print $this->totalMenus; ?>)
            </dt>
            <dd>Lista de Itens de Menus cadastrados</dd>
        </dl>
    </div>
    <!-- /btn -->
    <div class="btn-bottom"></div>
</div>
<!-- /Button -->
<!-- Button -->
<div class="btn-box">
    <div class="btn-top"></div>
    <div class="btn">
        <dl>
            <dt><a
                href="<?php echo $this->url(array('module' => 'menu', 'controller' => 'Index', 'action' => 'new'), 'admin', true) ?>">Novo</a>
            </dt>
            <dd>Cadastrar um novo Item de Menu</dd>
        </dl>
    </div>
    <!-- /btn -->
    <div class="btn-bottom"></div>
</div>
<!-- /Button -->
<div class="fix"></div>
<br/>