<script type="text/javascript">
    jQuery(function () {
        jQuery('table').tablesorter({
            sortList:[
                [0, 0]
            ],
            widgets:['zebra'],
            headers:{
                2:{
                    sorter:false
                },
                4:{
                    sorter:false
                }
            }
        });
    });
</script>

<div id="div-table">
    <table class="tablesorter" style="width: 100%;">
        <thead>
            <tr>
                <th>Id</th>
<!--                <th>Página</th>-->
                <th>Título</th>
                <th>Link</th>
                <th>Ordem</th>
                <th>&nbsp;</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($this->menus as $log): ?>
                <tr>
                    <td><?php print (int) $log->id; ?></td>
<!--                    <td><?php #print ($menu->page) ? $this->truncate($menu->page->title, 30) : null;    ?></td>-->
                    <td><?php print $this->truncate($log->title, 30); ?></td>
                    <td><?php print $this->truncate($log->link, 30); ?></td>
                    <td><?php print $this->escape($log->sequence); ?></td>
                    <td width="10%" style="text-align: center;">
                        <a href="<?php print $this->url(array('module' => 'menu', 'controller' => 'Index', 'action' => 'edit', 'id' => $log->id), 'admin', true); ?>"
                           style="margin-right: 10px" title="Editar">
                            <img src="<?php print $this->baseUrl('public/styles/design/ico-edit.gif'); ?>"/>
                        </a>
                        <a href="<?php print $this->url(array('module' => 'menu', 'controller' => 'Index', 'action' => 'delete', 'id' => $log->id), 'admin', true); ?>"
                           style="margin-right: 10px" title="Deletar">
                            <img src="<?php print $this->baseUrl('public/styles/design/ico-delete.gif'); ?>"/>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            <?php if (!$this->menus->count() > 0): ?>
                <tr>
                    <td colspan="5">Nenhum menu cadastrado.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>
