<script type="text/javascript">
    jQuery(function(){
        jQuery.datepicker.setDefaults( jQuery.datepicker.regional[ "pt-BR" ] );
        jQuery( "#date" ).datetimepicker({
            dateFormat: 'dd-mm-yy',
            dayNames: [
                'Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'
            ],
            dayNamesMin: [
                'D','S','T','Q','Q','S','S','D'
            ],
            dayNamesShort: [
                'Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'
            ],
            monthNames: [
                'Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro',
                'Outubro','Novembro','Dezembro'
            ],
            monthNamesShort: [
                'Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set',
                'Out','Nov','Dez'
            ],
            nextText: 'Próximo',
            prevText: 'Anterior'

        });
    });
</script>
<fieldset>
    <legend><?php print $this->legend; ?></legend>
    <?php print $this->form; ?>
</fieldset>