<script type="text/javascript">
    jQuery(function () {
        jQuery('table').tablesorter({
            sortList:[
                [0, 0]
            ],
            widgets:['zebra'],
            headers:{
                2:{
                    sorter:false
                },
                5:{
                    sorter:false
                }
            }
        });
    });
</script>

<div id="div-table">
    <table class="tablesorter" style="width: 100%;">
        <thead>
        <tr>
            <th>Id</th>
            <th>Título</th>
            <th>Url</th>
            <th>Criado</th>
            <th>Atualizado</th>
            <th>&nbsp;</th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($this->pages as $log): ?>
        <tr>
            <td><?php print (int)$log->id; ?></td>
            <td><?php print $this->escape($log->title); ?></td>
            <td><?php print $this->escape($log->url); ?></td>
            <td><?php print $this->dateToBr($log->created); ?></td>
            <td><?php print $this->dateToBr($log->updated); ?></td>
            <td width="10%" style="text-align: center;">
                <a href="<?php print $this->url(array('module' => 'page', 'controller' => 'Index', 'action' => 'edit', 'id' => $log->id), 'admin', true); ?>"
                   style="margin-right: 10px" title="Editar">
                    <img src="<?php print $this->baseUrl('public/styles/design/ico-edit.gif');?>"/>
                </a>
                <a href="<?php print $this->url(array('module' => 'page', 'controller' => 'Index', 'action' => 'delete', 'id' => $log->id), 'admin', true); ?>"
                   style="margin-right: 10px" title="Deletar">
                    <img src="<?php print $this->baseUrl('public/styles/design/ico-delete.gif');?>"/>
                </a>
            </td>
        </tr>
            <?php endforeach; ?>
        <?php if (!$this->pages->count() > 0): ?>
        <tr>
            <td colspan="6">Nenhuma página cadastrada.</td>
        </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>
