<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-type" content="text/html;charset=utf-8"/>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body id="login">

<div id="main-02">

    <div id="login-top"></div>

    <div id="login-box">

        <!-- Logo -->
        <p class="nom t-center"><a href="#"><img src="<?php print $this->baseUrl('public/index.png') ?>" alt="Index Digital" title="Index Digital"/></a></p>

        <!-- Messages -->
        <?php if ($this->messages && is_array($this->messages)): ?>
        <ul>
            <?php foreach ($this->messages as $message): ?>
            <p class="msg info"><?php print $message; ?></p>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>

        <!-- Form -->
        <?php print $this->layout()->content; ?>

    </div>
    <!-- /login-box -->

    <div id="login-bottom"></div>

</div>
<!-- /main -->

</body>
</html>