<?php $form = $this->form; ?>
<?php /** @var Zend_Form $form */ ?>
<script language="Javascript">
    var ImageCrop = {
        setCoords:function(c){
            $('#x').val(c.x);
            $('#y').val(c.y);
            $('#w').val(c.w);
            $('#h').val(c.h);
        }
    }
    
    jQuery(function() {
        jQuery('#target').Jcrop({
            minSize: [272,272],
            setSelect: [0,0,272,272],
            onChange: ImageCrop.setCoords,
            onSelect: ImageCrop.setCoords
        });
    });
</script>
<?php if ($form->getMessages()): ?>
    <ul class="msg error" style="background-image: none;">
        <?php foreach ($form->getMessages() as $erros): ?>
            <?php foreach ($erros as $error): ?>
                <li><?php print $error; ?></li>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<p class="box">
    
</p>
<img src="<?php print UPLOAD_URL . $this->timeline->image; ?>" id="target" />
<?php print $form; ?>