<script type="text/javascript">
    jQuery(function () {
        jQuery('table').tablesorter({
            sortList:[
                [0, 0]
            ],
            widgets:['zebra'],
            headers:{
                4:{
                    sorter:false
                }
            }
        });
    });
</script>

<div id="div-table">
    <table class="tablesorter" style="width: 100%;">
        <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Login</th>
            <th>&nbsp;</th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($this->users as $user): ?>
        <tr>
            <td><?php print (int)$user->id; ?></td>
            <td><?php print $this->escape($user->name); ?></td>
            <td><?php print $this->escape($user->email); ?></td>
            <td><?php print $this->escape($user->username); ?></td>
            <td width="10%" style="text-align: center;">
                <a href="<?php print $this->url(array('module' => 'user', 'controller' => 'Index', 'action' => 'edit', 'id' => $user->id), 'admin', true); ?>"
                   style="margin-right: 10px" title="Editar">
                    <img src="<?php print $this->baseUrl('public/styles/design/ico-edit.gif');?>"/>
                </a>
                <?php if ($user->role != 'admin'): ?>
                <a href="<?php print $this->url(array('module' => 'user', 'controller' => 'Index', 'action' => 'delete', 'id' => $user->id), 'admin', true); ?>"
                   style="margin-right: 10px" title="Deletar">
                    <img src="<?php print $this->baseUrl('public/styles/design/ico-delete.gif');?>"/>
                </a>
                <?php endif; ?>
            </td>
        </tr>
            <?php endforeach; ?>
        <?php if (!$this->users->count() > 0): ?>
        <tr>
            <td colspan="6">Nenhum usuário cadastrada.</td>
        </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>
